[module]
[[module.imports]]
    path = "gitlab.com/BluestNight/orbiter-server-nginx"
[[module.imports]]
    path = "gitlab.com/BluestNight/orbiter-comments-commento"
[[module.imports]]
    path = "gitlab.com/BluestNight/orbiter-sidebar-support"
[[module.imports]]
    path = "gitlab.com/BluestNight/orbiter-sidebar-search"
[[module.imports]]
    path = "gitlab.com/BluestNight/orbiter-sidebar-patreon"
[[module.imports]]
    path = "gitlab.com/BluestNight/orbiter-shortcode-katex"
[[module.imports]]
    path = "gitlab.com/BluestNight/orbiter-server-netlify"
[[module.mounts]]
    source = "archetypes"
    target = "archetypes"
[[module.mounts]]
    source = "assets"
    target = "assets"
[[module.mounts]]
    source = "data"
    target = "data"
[[module.mounts]]
    source = "i18n"
    target = "i18n"
[[module.mounts]]
    source = "layouts"
    target = "layouts"
[[module.mounts]]
    source = "static"
    target = "static"

[params]
[params.color]
    page_background = "#000000"
    main_background = "#050505"
    alt_background = "#252525"
    main_text = "#e2e2e2"
    alt_text = "#e2e2e2"
    accent = "#2c8cef"
    accent_text = "#e2e2e2"

[params.fonts]
    header_style = "sans-serif"
    body_style = "sans-serif"
    print_header_style = "sans-serif"
    print_body_style = "serif"

[params.shortcodes]
    [params.shortcodes.handwriting]
        [params.shortcodes.handwriting.head]
            path = "shortcodes/handwriting/head.html"
            cache = true
    [params.shortcodes.tabgroup]
        [params.shortcodes.tabgroup.head]
            path = "shortcodes/tabgroup/head.html"
            cache = true
    [params.shortcodes.table]
        [params.shortcodes.table.head]
            path = "shortcodes/table/head.html"
            cache = true
    [params.shortcodes.nebula-form]
        [params.shortcodes.nebula-form.foot]
            path = "shortcodes/nebula-form/foot.html"
            cache = true
        [params.shortcodes.nebula-form.csp]
        [params.shortcodes.nebula-form.csp.connect-src]
            path = "shortcodes/forms/csp/connect"
    [params.shortcodes.netlify-form]
        [params.shortcodes.netlify-form.csp]
        [params.shortcodes.netlify-form.csp.connect-src]
            path = "shortcodes/forms/csp/connect"
            cache = true


[params.sidebar]
    [params.sidebar.categories]
        [params.sidebar.categories.partial]
            path = "sidebar/widgets/categories/widget.html"
            cache = true
    [params.sidebar.recent]
        [params.sidebar.recent.partial]
            path = "sidebar/widgets/recent/widget.html"
    [params.sidebar.taglist]
        [params.sidebar.taglist.head]
            path = "sidebar/widgets/taglist/head.html"
            cache = true
        [params.sidebar.taglist.partial]
            path = "sidebar/widgets/taglist/widget.html"
            cache = true

[mediaTypes]
    [mediaTypes."config/caddy"]
        suffixes = ["Caddyfile"]
        delimiter = ""

[outputFormats]
    [outputFormats.Caddyfile]
        isPlainText = true
        basename = ""
        mediaType = "config/caddy"
        notAlternative = true
