[params]
[params.Midnight]
[params.Midnight.color]
    page_background = "#000000"
    main_background = "#050505"
    alt_background = "#252525"
    main_text = "#e2e2e2"
    alt_text = "#e2e2e2"
    accent = "#2c8cef"
    accent_text = "#e2e2e2"

[params.Midnight.fonts]
    header_style = "sans-serif"
    body_style = "sans-serif"
    print_header_style = "sans-serif"
    print_body_style = "serif"

[params.Midnight.shortcodes]
    [params.Midnight.shortcodes.handwriting]
        [params.Midnight.shortcodes.handwriting.head]
            path = "shortcodes/handwriting/head.html"
            cache = true
    [params.Midnight.shortcodes.tabgroup]
        [params.Midnight.shortcodes.tabgroup.head]
            path = "shortcodes/tabgroup/head.html"
            cache = true
    [params.Midnight.shortcodes.table]
        [params.Midnight.shortcodes.table.head]
            path = "shortcodes/table/head.html"
            cache = true
    [params.Midnight.shortcodes.nebula-form]
        [params.Midnight.shortcodes.nebula-form.foot]
            path = "shortcodes/nebula-form/foot.html"
            cache = true
        [params.Midnight.shortcodes.nebula-form.csp]
        [params.Midnight.shortcodes.nebula-form.csp.connect-src]
            path = "shortcodes/forms/csp/connect"
    [params.Midnight.shortcodes.netlify-form]
        [params.Midnight.shortcodes.netlify-form.csp]
        [params.Midnight.shortcodes.netlify-form.csp.connect-src]
            path = "shortcodes/forms/csp/connect"
            cache = true


[params.Midnight.sidebar]
    [params.Midnight.sidebar.categories]
        [params.Midnight.sidebar.categories.partial]
            path = "sidebar/widgets/categories/widget.html"
            cache = true
    [params.Midnight.sidebar.recent]
        [params.Midnight.sidebar.recent.partial]
            path = "sidebar/widgets/recent/widget.html"
    [params.Midnight.sidebar.taglist]
        [params.Midnight.sidebar.taglist.head]
            path = "sidebar/widgets/taglist/head.html"
            cache = true
        [params.Midnight.sidebar.taglist.partial]
            path = "sidebar/widgets/taglist/widget.html"
            cache = true

[mediaTypes]
    [mediaTypes."netlify/headers"]
        suffixes = ["_headers"]
        delimiter = ""
    [mediaTypes."config/caddy"]
        suffixes = ["Caddyfile"]
        delimiter = ""

[outputFormats]
    [outputFormats.NetlifyHeaders]
        isPlainText = true
        basename = ""
        mediaType = "netlify/headers"
        notAlternative = true
    [outputFormats.Caddyfile]
        isPlainText = true
        basename = ""
        mediaType = "config/caddy"
        notAlternative = true
